version: "2"
services:
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
      
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  front-end:
    container_name: front-end
    restart: always
    build: ./front
    ports:
      - "4200:80"

  node-microservice:
    container_name: node-microservice
    restart: always
    build: ./node server
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo

  spring-microservice:
    container_name: spring-microservice
    restart: always
    build: ./spring server
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run

  
    