version: "2"
services:
  node-microservice:
    container_name: node-microservice
    build: ./node
    ports:
      - "3000:3000"
    links:
      - mongo

  front-end:
    container_name: front-end
    build: ./front
    ports:
      - "4200:4200"

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    